config/routes.rb
Rails.application.routes.draw do
  resources :spots
  root 'pages#about'
  get 'pages/about'
  get 'pages/history'
  get 'signup', to: 'users#new'
  post 'book', to: 'spots#book'
  post 'free', to: 'spots#free'


  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post '/slack/command', to: 'slack/commands#create'
  post '/slack/register', to: 'slack/commands#register'
  post '/slack/show', to: 'slack/commands#show'

  post '/auth/slack/callback', to: 'omniauth_callbacks#slack'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/spot.rb
class Spot < ApplicationRecord
  has_many :histories
  has_many :users, through: :histories
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:update, :destroy]
  before_action :require_user, except: [:index]
  # before_action :require_same_user, only: [:update]
  # before_action :require_same_user, only: [:edit, :update, :destroy]


  def free
    spot = Spot.find(params[:format])
    spot.reserved = false
    spot.save
    redirect_to spots_url
  end

  def book
    spot = Spot.find(params[:format])
    spot.reserved = true
    spot.save
    history = History.new(user_id: current_user.id, spot_id: spot.id)
    history.save
    # byebug
    redirect_to spots_url
  end

  def index
    @spots = Spot.all.order(id: :asc)
    @users = User.all
    @history = History.all
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new(spot_params)
    # @spot.user = current_user
    if @spot.save
      flash[:notice] = "Spot was created successfully."
      redirect_to @spot
    else
      render 'new'
    end
  end

  def update
    if (set_spot.reserved != true)
      spot = set_spot        # Search a spot in database by id
      user = current_user
      history = History.new(user_id: user.id, spot_id: spot.id)
      history.save
      if history.save
        flash[:notice] = "User #{user.full_name} reserved spot #{spot.name}"
      end
      # byebug
    end

    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to @spot , notice: 'Spot was successfully updated.'}
        format.json { render :show, status: :ok, location: @spot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @spot.destroy
    respond_to do |format|
      format.html { redirect_to spots_url, notice: 'Spot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_spot
    @spot = Spot.find(params[:id])
  end

  def spot_params
    params.require(:spot).permit(:name, :reserved)
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_form.html.erb
<%= form_with(model: spot) do |form| %>
  <% if spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
        <% spot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :reserved %>
    <%= form.check_box :reserved %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spots/index.html.erb
<h1>Free parking spots</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @spots.each do |spot| %>
      <tr>
        <% who=@history.where(spot_id: spot.id).last.user_id if spot.reserved == true %>
        <th scope="col"><%= spot.name %></th>
        <td><%= spot.reserved == true ? "Reserved by #{@users.find(who).full_name}" : 'Free spot' %></td>
        <% if logged_in? && spot.reserved == false %>
          <td><%= button_to 'Book it', book_path(spot), class: "btn btn-success btn-sm d-grid gap-2"  %></td>
<!--      <td><%#= link_to 'Destroy', spot, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        <% elsif logged_in? && spot.reserved == true && current_user.id == who || @users.find(who).id == 0 %>
          <td><%= button_to 'Delete reservation', free_path(spot), class: "btn btn-danger btn-sm d-grid gap-2"  %></td>
        <% else %>
          <th></th>
        <% end %>
        <%# if logged_in? && spot.reserved == true && current_user.id == who %>
<!--          <td><%#= button_to 'Delete reservations', free_path(spot), class: "btn btn-danger"  %></td>-->
        <%# end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spots/new.html.erb
<h1>New Spot</h1>

<%= render 'form', spot: @spot %>

<%= link_to 'Back', spots_path %>