config/routes.rb
Rails.application.routes.draw do
  resources :spots
  root 'pages#about'
  get 'pages/about'
  get 'pages/history'
  get 'signup', to: 'users#new'
  post 'book', to: 'spots#book'
  post 'free', to: 'spots#free'


  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post '/slack/command', to: 'slack/commands#create'
  post '/slack/register', to: 'slack/commands#register'
  post '/slack/show', to: 'slack/commands#show'

  post '/auth/slack/callback', to: 'omniauth_callbacks#slack'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/_history.html.erb
<table>
  <thead>
  <tr>
    <th>Spot name</th>
  </tr>
  </thead>

  <tbody>
  <% @histories.each do |history| %>
    <% if history.spot.reserved == true %>
      <tr>
        <td><%= history.spot.name %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/pages/about.html.erb
<h1>Instruction</h1>
</br>
<h4>Registering a Slack account with the <b>/register</b> command</h4>
<p>
  To register a Slack account in this app you need to register a regular account first: <b>Log in > Sign up</b>.
  When registering, you need to write a six-character "Slack register",
  this is the id by which you will be able to associate your Slack account with the account in the application.
</p>
<p>
  Once you've registered an in-app account, you'll need to accept the Slack "Pro" invitation.
  To associate your account with a previously registered account in the application, you must enter the <b>/register (slack register)</b>  command,
  where (slack register) is the six-character "Slack register" entered during registration.
  If everything goes correctly, you will receive the message "The account has been registered with (account name)"
</p>
<p>
  If you do not register a Slack account,
  all reserved parking spots will be assigned to the (Unverified user) and any logged in user will be able to delete this reservation.
</p>
</br>
<h4>Reservation of parking spots with Slack <b>/book</b> command </h4>
<p>
  To reserve a parking spot using Slack, you must enter the <b>/book (name of spot)</b> command.
  If the spot is properly reserved, you will receive an answer "User (account name) reserved spot (name of spot)".
  If the place is reserved you will receive "Spot (name of spot) is currently reserved".
  Or if the place doesn't exist "Selected spot doesn't exist".
</p>
</br>
<h4>Showing reserved parking spots with Slack <b>/show</b> command </h4>
<p>
  To see reserved parking spots, use the <b>/show</b> command
</p>

app/views/pages/history.html.erb
<h1>Parking spot history</h1>

<div class="flickr_pagination">
  <%= will_paginate @histories, :container => false %>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Spot name</th>
      <th scope="col">Reserved by</th>
      <th scope="col">Reserved at</th>
    </tr>
  </thead>

  <tbody>
  <% @histories.each do |history| %>
    <tr>
      <th scope="col"><%= history.spot.name %></th>
      <td><%= history.user.full_name if history.user %></td>
      <%# if history.spot.reserved == true && history.user[:full_name] == 'Unverified user' %>
<!--        <td><%#= link_to 'Edit', edit_spot_path(history.spot) %></td>-->
      <%# end %>
      <td><%= history.updated_at.in_time_zone('Warsaw').to_time.to_formatted_s :long_ordinal if history.user %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="flickr_pagination">
  <%= will_paginate @histories, :container => false %>
</div>

app/views/pages/home.html.erb
<h1>Parking App</h1>
<p>App for booking parking spots</p>